### ISSUE TITLE
The Datasets

### ISSUE THREAD

**Issue by jinchm** [tommorris/dbpedia-tests#1]
Thank you for sharing the code
Can you provide the datasets. The train and test.
my e-mail: jinchm123@163.com
Thank you.

**Comment by tommorris** [comment]
The purpose of this (quite ancient) project is to have some tests for DBpedia, the RDF scrape of Wikipedia. You can [download the dataset here](http://wiki.dbpedia.org/downloads-2016-04) or [query it online here](http://wiki.dbpedia.org/OnlineAccess). These tests only exist to sanity-check DBpedia.
